/*
 * This file is generated by jOOQ.
 */
package org.lattejava.app.db.jooq.tables.records;


import java.time.Instant;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.lattejava.app.db.jooq.tables.GroupVerifications;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GroupVerificationsRecord extends UpdatableRecordImpl<GroupVerificationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.group_verifications.group_name</code>.
     */
    public void setGroupName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.group_verifications.group_name</code>.
     */
    public String getGroupName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.group_verifications.started_at</code>.
     */
    public void setStartedAt(Instant value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.group_verifications.started_at</code>.
     */
    public Instant getStartedAt() {
        return (Instant) get(1);
    }

    /**
     * Setter for <code>public.group_verifications.last_checked_at</code>.
     */
    public void setLastCheckedAt(Instant value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.group_verifications.last_checked_at</code>.
     */
    public Instant getLastCheckedAt() {
        return (Instant) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupVerificationsRecord
     */
    public GroupVerificationsRecord() {
        super(GroupVerifications.GROUP_VERIFICATIONS);
    }

    /**
     * Create a detached, initialised GroupVerificationsRecord
     */
    public GroupVerificationsRecord(String groupName, Instant startedAt, Instant lastCheckedAt) {
        super(GroupVerifications.GROUP_VERIFICATIONS);

        setGroupName(groupName);
        setStartedAt(startedAt);
        setLastCheckedAt(lastCheckedAt);
        resetTouchedOnNotNull();
    }
}
