/*
 * This file is generated by jOOQ.
 */
package org.lattejava.app.db.jooq.tables.records;


import java.time.Instant;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.lattejava.app.db.jooq.tables.Groups;
import org.lattejava.app.model.GroupState;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GroupsRecord extends UpdatableRecordImpl<GroupsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.groups.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.groups.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.groups.description</code>.
     */
    public void setDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.groups.description</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.groups.state</code>.
     */
    public void setState(GroupState value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.groups.state</code>.
     */
    public GroupState getState() {
        return (GroupState) get(2);
    }

    /**
     * Setter for <code>public.groups.verification_code</code>.
     */
    public void setVerificationCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.groups.verification_code</code>.
     */
    public String getVerificationCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.groups.created_at</code>.
     */
    public void setCreatedAt(Instant value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.groups.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(4);
    }

    /**
     * Setter for <code>public.groups.verified_at</code>.
     */
    public void setVerifiedAt(Instant value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.groups.verified_at</code>.
     */
    public Instant getVerifiedAt() {
        return (Instant) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupsRecord
     */
    public GroupsRecord() {
        super(Groups.GROUPS);
    }

    /**
     * Create a detached, initialised GroupsRecord
     */
    public GroupsRecord(String name, String description, GroupState state, String verificationCode, Instant createdAt, Instant verifiedAt) {
        super(Groups.GROUPS);

        setName(name);
        setDescription(description);
        setState(state);
        setVerificationCode(verificationCode);
        setCreatedAt(createdAt);
        setVerifiedAt(verifiedAt);
        resetTouchedOnNotNull();
    }
}
