/*
 * This file is generated by jOOQ.
 */
package org.lattejava.app.db.jooq.tables.records;


import java.time.Instant;
import java.util.UUID;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.lattejava.app.db.jooq.tables.Members;
import org.lattejava.app.model.MembershipState;
import org.lattejava.app.model.Role;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MembersRecord extends UpdatableRecordImpl<MembersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.members.group_name</code>.
     */
    public void setGroupName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.members.group_name</code>.
     */
    public String getGroupName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.members.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.members.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.members.role</code>.
     */
    public void setRole(Role value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.members.role</code>.
     */
    public Role getRole() {
        return (Role) get(2);
    }

    /**
     * Setter for <code>public.members.state</code>.
     */
    public void setState(MembershipState value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.members.state</code>.
     */
    public MembershipState getState() {
        return (MembershipState) get(3);
    }

    /**
     * Setter for <code>public.members.invited_by</code>.
     */
    public void setInvitedBy(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.members.invited_by</code>.
     */
    public UUID getInvitedBy() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.members.invited_at</code>.
     */
    public void setInvitedAt(Instant value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.members.invited_at</code>.
     */
    public Instant getInvitedAt() {
        return (Instant) get(5);
    }

    /**
     * Setter for <code>public.members.joined_at</code>.
     */
    public void setJoinedAt(Instant value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.members.joined_at</code>.
     */
    public Instant getJoinedAt() {
        return (Instant) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MembersRecord
     */
    public MembersRecord() {
        super(Members.MEMBERS);
    }

    /**
     * Create a detached, initialised MembersRecord
     */
    public MembersRecord(String groupName, UUID userId, Role role, MembershipState state, UUID invitedBy, Instant invitedAt, Instant joinedAt) {
        super(Members.MEMBERS);

        setGroupName(groupName);
        setUserId(userId);
        setRole(role);
        setState(state);
        setInvitedBy(invitedBy);
        setInvitedAt(invitedAt);
        setJoinedAt(joinedAt);
        resetTouchedOnNotNull();
    }
}
