/*
 * This file is generated by jOOQ.
 */
package org.lattejava.app.db.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.lattejava.app.db.jooq.tables.Versions;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VersionsRecord extends UpdatableRecordImpl<VersionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.versions.version</code>.
     */
    public void setVersion(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.versions.version</code>.
     */
    public String getVersion() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.versions.checksum</code>.
     */
    public void setChecksum(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.versions.checksum</code>.
     */
    public String getChecksum() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.versions.installed_instant</code>.
     */
    public void setInstalledInstant(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.versions.installed_instant</code>.
     */
    public Long getInstalledInstant() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VersionsRecord
     */
    public VersionsRecord() {
        super(Versions.VERSIONS);
    }

    /**
     * Create a detached, initialised VersionsRecord
     */
    public VersionsRecord(String version, String checksum, Long installedInstant) {
        super(Versions.VERSIONS);

        setVersion(version);
        setChecksum(checksum);
        setInstalledInstant(installedInstant);
        resetTouchedOnNotNull();
    }
}
