db.password=dev
db.url=jdbc:postgresql://127.0.0.1:5432/app
db.username=dev
fusionauth.apiKey=33052c8a-c283-4e96-9d2a-eb1215c69f8f-not-for-prod
fusionauth.baseUrl=https://auth.local.lattejava.org:9413
fusionauth.cliClientId=cc5f3c9e-b28e-4632-bafe-823363669820
fusionauth.cliClientSecret=super-secret-secret-that-should-be-regenerated-for-production
fusionauth.clientId=e9fdb985-9173-4e01-9d73-ac2d60d1dc8e
fusionauth.clientSecret=super-secret-secret-that-should-be-regenerated-for-production
fusionauth.issuer=https://auth.local.lattejava.org:9413
github.clientId=replace-me
github.clientSecret=replace-me
s3.accessKeyId=latte-test
s3.bucket=latte-test
s3.endpoint=http://localhost:9000
s3.region=us-east-1
s3.secretAccessKey=latte-test-secret
web.cookieEncryptionKey=PM9YYVcx+Z9/cfxLBzjOb5uXxRG2+TrUHPK9mizQUR8=
