/*
 * This file is generated by jOOQ.
 */
package org.lattejava.app.db.jooq.tables;


import java.time.Instant;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Converter;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.lattejava.app.db.jooq.Keys;
import org.lattejava.app.db.jooq.Public;
import org.lattejava.app.db.jooq.tables.GroupVerifications.GroupVerificationsPath;
import org.lattejava.app.db.jooq.tables.Members.MembersPath;
import org.lattejava.app.db.jooq.tables.records.GroupsRecord;
import org.lattejava.app.model.GroupState;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Groups extends TableImpl<GroupsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.groups</code>
     */
    public static final Groups GROUPS = new Groups();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GroupsRecord> getRecordType() {
        return GroupsRecord.class;
    }

    /**
     * The column <code>public.groups.name</code>.
     */
    public final TableField<GroupsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.groups.description</code>.
     */
    public final TableField<GroupsRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.groups.state</code>.
     */
    public final TableField<GroupsRecord, GroupState> STATE = createField(DSL.name("state"), SQLDataType.CLOB.nullable(false), this, "", Converter.ofNullable(String.class, GroupState.class, t -> t == null ? null : org.lattejava.app.model.GroupState.valueOf(t), u -> u == null ? null : u.name()));

    /**
     * The column <code>public.groups.verification_code</code>.
     */
    public final TableField<GroupsRecord, String> VERIFICATION_CODE = createField(DSL.name("verification_code"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.groups.created_at</code>.
     */
    public final TableField<GroupsRecord, Instant> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.BIGINT.nullable(false), this, "", Converter.ofNullable(Long.class, Instant.class, t -> t == null ? null : java.time.Instant.ofEpochMilli(t), u -> u == null ? null : u.toEpochMilli()));

    /**
     * The column <code>public.groups.verified_at</code>.
     */
    public final TableField<GroupsRecord, Instant> VERIFIED_AT = createField(DSL.name("verified_at"), SQLDataType.BIGINT, this, "", Converter.ofNullable(Long.class, Instant.class, t -> t == null ? null : java.time.Instant.ofEpochMilli(t), u -> u == null ? null : u.toEpochMilli()));

    private Groups(Name alias, Table<GroupsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Groups(Name alias, Table<GroupsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.groups</code> table reference
     */
    public Groups(String alias) {
        this(DSL.name(alias), GROUPS);
    }

    /**
     * Create an aliased <code>public.groups</code> table reference
     */
    public Groups(Name alias) {
        this(alias, GROUPS);
    }

    /**
     * Create a <code>public.groups</code> table reference
     */
    public Groups() {
        this(DSL.name("groups"), null);
    }

    public <O extends Record> Groups(Table<O> path, ForeignKey<O, GroupsRecord> childPath, InverseForeignKey<O, GroupsRecord> parentPath) {
        super(path, childPath, parentPath, GROUPS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GroupsPath extends Groups implements Path<GroupsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> GroupsPath(Table<O> path, ForeignKey<O, GroupsRecord> childPath, InverseForeignKey<O, GroupsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GroupsPath(Name alias, Table<GroupsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GroupsPath as(String alias) {
            return new GroupsPath(DSL.name(alias), this);
        }

        @Override
        public GroupsPath as(Name alias) {
            return new GroupsPath(alias, this);
        }

        @Override
        public GroupsPath as(Table<?> alias) {
            return new GroupsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<GroupsRecord> getPrimaryKey() {
        return Keys.GROUPS_PKEY;
    }

    private transient GroupVerificationsPath _groupVerifications;

    /**
     * Get the implicit to-many join path to the
     * <code>public.group_verifications</code> table
     */
    public GroupVerificationsPath groupVerifications() {
        if (_groupVerifications == null)
            _groupVerifications = new GroupVerificationsPath(this, null, Keys.GROUP_VERIFICATIONS__GROUP_VERIFICATIONS_GROUP_NAME_FKEY.getInverseKey());

        return _groupVerifications;
    }

    private transient MembersPath _members;

    /**
     * Get the implicit to-many join path to the <code>public.members</code>
     * table
     */
    public MembersPath members() {
        if (_members == null)
            _members = new MembersPath(this, null, Keys.MEMBERS__MEMBERS_GROUP_NAME_FKEY.getInverseKey());

        return _members;
    }

    @Override
    public List<Check<GroupsRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("groups_state_check"), "((state = ANY (ARRAY['VERIFIED'::text, 'PENDING'::text, 'FAILED'::text])))", true)
        );
    }

    @Override
    public Groups as(String alias) {
        return new Groups(DSL.name(alias), this);
    }

    @Override
    public Groups as(Name alias) {
        return new Groups(alias, this);
    }

    @Override
    public Groups as(Table<?> alias) {
        return new Groups(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Groups rename(String name) {
        return new Groups(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Groups rename(Name name) {
        return new Groups(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Groups rename(Table<?> name) {
        return new Groups(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Groups where(Condition condition) {
        return new Groups(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Groups where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Groups where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Groups where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Groups where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Groups where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Groups where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Groups where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Groups whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Groups whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
