/*
 * This file is generated by jOOQ.
 */
package org.lattejava.app.db.jooq.tables;


import java.time.Instant;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Converter;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.lattejava.app.db.jooq.Keys;
import org.lattejava.app.db.jooq.Public;
import org.lattejava.app.db.jooq.tables.Groups.GroupsPath;
import org.lattejava.app.db.jooq.tables.records.GroupVerificationsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GroupVerifications extends TableImpl<GroupVerificationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.group_verifications</code>
     */
    public static final GroupVerifications GROUP_VERIFICATIONS = new GroupVerifications();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GroupVerificationsRecord> getRecordType() {
        return GroupVerificationsRecord.class;
    }

    /**
     * The column <code>public.group_verifications.group_name</code>.
     */
    public final TableField<GroupVerificationsRecord, String> GROUP_NAME = createField(DSL.name("group_name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.group_verifications.started_at</code>.
     */
    public final TableField<GroupVerificationsRecord, Instant> STARTED_AT = createField(DSL.name("started_at"), SQLDataType.BIGINT.nullable(false), this, "", Converter.ofNullable(Long.class, Instant.class, t -> t == null ? null : java.time.Instant.ofEpochMilli(t), u -> u == null ? null : u.toEpochMilli()));

    /**
     * The column <code>public.group_verifications.last_checked_at</code>.
     */
    public final TableField<GroupVerificationsRecord, Instant> LAST_CHECKED_AT = createField(DSL.name("last_checked_at"), SQLDataType.BIGINT, this, "", Converter.ofNullable(Long.class, Instant.class, t -> t == null ? null : java.time.Instant.ofEpochMilli(t), u -> u == null ? null : u.toEpochMilli()));

    private GroupVerifications(Name alias, Table<GroupVerificationsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GroupVerifications(Name alias, Table<GroupVerificationsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.group_verifications</code> table reference
     */
    public GroupVerifications(String alias) {
        this(DSL.name(alias), GROUP_VERIFICATIONS);
    }

    /**
     * Create an aliased <code>public.group_verifications</code> table reference
     */
    public GroupVerifications(Name alias) {
        this(alias, GROUP_VERIFICATIONS);
    }

    /**
     * Create a <code>public.group_verifications</code> table reference
     */
    public GroupVerifications() {
        this(DSL.name("group_verifications"), null);
    }

    public <O extends Record> GroupVerifications(Table<O> path, ForeignKey<O, GroupVerificationsRecord> childPath, InverseForeignKey<O, GroupVerificationsRecord> parentPath) {
        super(path, childPath, parentPath, GROUP_VERIFICATIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GroupVerificationsPath extends GroupVerifications implements Path<GroupVerificationsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> GroupVerificationsPath(Table<O> path, ForeignKey<O, GroupVerificationsRecord> childPath, InverseForeignKey<O, GroupVerificationsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GroupVerificationsPath(Name alias, Table<GroupVerificationsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GroupVerificationsPath as(String alias) {
            return new GroupVerificationsPath(DSL.name(alias), this);
        }

        @Override
        public GroupVerificationsPath as(Name alias) {
            return new GroupVerificationsPath(alias, this);
        }

        @Override
        public GroupVerificationsPath as(Table<?> alias) {
            return new GroupVerificationsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<GroupVerificationsRecord> getPrimaryKey() {
        return Keys.GROUP_VERIFICATIONS_PKEY;
    }

    @Override
    public List<ForeignKey<GroupVerificationsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.GROUP_VERIFICATIONS__GROUP_VERIFICATIONS_GROUP_NAME_FKEY);
    }

    private transient GroupsPath _groups;

    /**
     * Get the implicit join path to the <code>public.groups</code> table.
     */
    public GroupsPath groups() {
        if (_groups == null)
            _groups = new GroupsPath(this, Keys.GROUP_VERIFICATIONS__GROUP_VERIFICATIONS_GROUP_NAME_FKEY, null);

        return _groups;
    }

    @Override
    public GroupVerifications as(String alias) {
        return new GroupVerifications(DSL.name(alias), this);
    }

    @Override
    public GroupVerifications as(Name alias) {
        return new GroupVerifications(alias, this);
    }

    @Override
    public GroupVerifications as(Table<?> alias) {
        return new GroupVerifications(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupVerifications rename(String name) {
        return new GroupVerifications(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupVerifications rename(Name name) {
        return new GroupVerifications(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupVerifications rename(Table<?> name) {
        return new GroupVerifications(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupVerifications where(Condition condition) {
        return new GroupVerifications(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupVerifications where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupVerifications where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupVerifications where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupVerifications where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupVerifications where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupVerifications where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupVerifications where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupVerifications whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupVerifications whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
