/*
 * This file is generated by jOOQ.
 */
package org.lattejava.app.db.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.lattejava.app.db.jooq.Keys;
import org.lattejava.app.db.jooq.Public;
import org.lattejava.app.db.jooq.tables.records.VersionsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Versions extends TableImpl<VersionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.versions</code>
     */
    public static final Versions VERSIONS = new Versions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VersionsRecord> getRecordType() {
        return VersionsRecord.class;
    }

    /**
     * The column <code>public.versions.version</code>.
     */
    public final TableField<VersionsRecord, String> VERSION = createField(DSL.name("version"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.versions.checksum</code>.
     */
    public final TableField<VersionsRecord, String> CHECKSUM = createField(DSL.name("checksum"), SQLDataType.CHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.versions.installed_instant</code>.
     */
    public final TableField<VersionsRecord, Long> INSTALLED_INSTANT = createField(DSL.name("installed_instant"), SQLDataType.BIGINT.nullable(false), this, "");

    private Versions(Name alias, Table<VersionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Versions(Name alias, Table<VersionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.versions</code> table reference
     */
    public Versions(String alias) {
        this(DSL.name(alias), VERSIONS);
    }

    /**
     * Create an aliased <code>public.versions</code> table reference
     */
    public Versions(Name alias) {
        this(alias, VERSIONS);
    }

    /**
     * Create a <code>public.versions</code> table reference
     */
    public Versions() {
        this(DSL.name("versions"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<VersionsRecord> getPrimaryKey() {
        return Keys.VERSIONS_PKEY;
    }

    @Override
    public Versions as(String alias) {
        return new Versions(DSL.name(alias), this);
    }

    @Override
    public Versions as(Name alias) {
        return new Versions(alias, this);
    }

    @Override
    public Versions as(Table<?> alias) {
        return new Versions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Versions rename(String name) {
        return new Versions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Versions rename(Name name) {
        return new Versions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Versions rename(Table<?> name) {
        return new Versions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Versions where(Condition condition) {
        return new Versions(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Versions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Versions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Versions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Versions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Versions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Versions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Versions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Versions whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Versions whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
