/*
 * This file is generated by jOOQ.
 */
package org.lattejava.app.db.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.lattejava.app.db.jooq.tables.Members;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index MEMBERS_USER_ID_IDX = Internal.createIndex(DSL.name("members_user_id_idx"), Members.MEMBERS, new OrderField[] { Members.MEMBERS.USER_ID }, false);
}
