/*
 * This file is generated by jOOQ.
 */
package org.lattejava.app.db.jooq;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;
import org.lattejava.app.db.jooq.tables.GroupVerifications;
import org.lattejava.app.db.jooq.tables.Groups;
import org.lattejava.app.db.jooq.tables.Members;
import org.lattejava.app.db.jooq.tables.Versions;
import org.lattejava.app.db.jooq.tables.records.GroupVerificationsRecord;
import org.lattejava.app.db.jooq.tables.records.GroupsRecord;
import org.lattejava.app.db.jooq.tables.records.MembersRecord;
import org.lattejava.app.db.jooq.tables.records.VersionsRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<GroupVerificationsRecord> GROUP_VERIFICATIONS_PKEY = Internal.createUniqueKey(GroupVerifications.GROUP_VERIFICATIONS, DSL.name("group_verifications_pkey"), new TableField[] { GroupVerifications.GROUP_VERIFICATIONS.GROUP_NAME }, true);
    public static final UniqueKey<GroupsRecord> GROUPS_PKEY = Internal.createUniqueKey(Groups.GROUPS, DSL.name("groups_pkey"), new TableField[] { Groups.GROUPS.NAME }, true);
    public static final UniqueKey<MembersRecord> MEMBERS_PKEY = Internal.createUniqueKey(Members.MEMBERS, DSL.name("members_pkey"), new TableField[] { Members.MEMBERS.GROUP_NAME, Members.MEMBERS.USER_ID }, true);
    public static final UniqueKey<VersionsRecord> VERSIONS_PKEY = Internal.createUniqueKey(Versions.VERSIONS, DSL.name("versions_pkey"), new TableField[] { Versions.VERSIONS.VERSION }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<GroupVerificationsRecord, GroupsRecord> GROUP_VERIFICATIONS__GROUP_VERIFICATIONS_GROUP_NAME_FKEY = Internal.createForeignKey(GroupVerifications.GROUP_VERIFICATIONS, DSL.name("group_verifications_group_name_fkey"), new TableField[] { GroupVerifications.GROUP_VERIFICATIONS.GROUP_NAME }, Keys.GROUPS_PKEY, new TableField[] { Groups.GROUPS.NAME }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<MembersRecord, GroupsRecord> MEMBERS__MEMBERS_GROUP_NAME_FKEY = Internal.createForeignKey(Members.MEMBERS, DSL.name("members_group_name_fkey"), new TableField[] { Members.MEMBERS.GROUP_NAME }, Keys.GROUPS_PKEY, new TableField[] { Groups.GROUPS.NAME }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
}
