/*
 * This file is generated by jOOQ.
 */
package org.lattejava.app.db.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;
import org.lattejava.app.db.jooq.tables.GroupVerifications;
import org.lattejava.app.db.jooq.tables.Groups;
import org.lattejava.app.db.jooq.tables.Members;


/**
 * standard public schema
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.group_verifications</code>.
     */
    public final GroupVerifications GROUP_VERIFICATIONS = GroupVerifications.GROUP_VERIFICATIONS;

    /**
     * The table <code>public.groups</code>.
     */
    public final Groups GROUPS = Groups.GROUPS;

    /**
     * The table <code>public.members</code>.
     */
    public final Members MEMBERS = Members.MEMBERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            GroupVerifications.GROUP_VERIFICATIONS,
            Groups.GROUPS,
            Members.MEMBERS
        );
    }
}
