/*
 * This file is generated by jOOQ.
 */
package org.lattejava.app.db.jooq;


import org.lattejava.app.db.jooq.tables.GroupVerifications;
import org.lattejava.app.db.jooq.tables.Groups;
import org.lattejava.app.db.jooq.tables.Members;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.group_verifications</code>.
     */
    public static final GroupVerifications GROUP_VERIFICATIONS = GroupVerifications.GROUP_VERIFICATIONS;

    /**
     * The table <code>public.groups</code>.
     */
    public static final Groups GROUPS = Groups.GROUPS;

    /**
     * The table <code>public.members</code>.
     */
    public static final Members MEMBERS = Members.MEMBERS;
}
